//
//  CategoryConstants.swift
//  Dengage.Framework
//
//  Created by Ekin Bulut on 18.03.2020.
//

import Foundation

// MARK:- ACTION TYPES AND CATEGORIES
let YES_ACTION = "YES_ACTION"
let NO_ACTION = "NO_ACTION"

let ACCEPT_ACTION = "ACCEPT_ACTION"
let DECLINE_ACTION = "DECLINE_ACTION"

let CONFIRM_ACTION = "CONFIRM_ACTION"
let CANCEL_ACTION = "CANCEL_ACTION"

let PREVIOUS_ACTION = "PREVIOUS_ACTION"
let NEXT_ACTION = "NEXT_ACTION"

let SIMPLE_CATEGORY = "DENGAGE_SIMPLE_CATEGORY"
let ASK_CATEGORY = "DENGAGE_ASK_CATEGORY"
let CONFIRM_CATEGORY = "DENGAGE_CONFIRM_CATEGORY"
let CAROUSEL_CATEGORY = "DENGAGE_CAROUSEL_CATEGORY"
